package cli

import (
	"sort"
	"strings"

	"github.com/alecthomas/kong"

	"github.com/phall1/blackbird/internal/cli/render"
)

// CompletionCmd prints a shell completion script generated by walking Kong's
// own model. Nothing here is hand-maintained and no completion library is
// linked: a new command appears in all three shells the moment it is declared.
type CompletionCmd struct {
	Shell string `arg:"" enum:"bash,zsh,fish" default:"bash" help:"Shell to generate a completion script for."`
}

// Help is Kong's HelpProvider hook.
func (cmd *CompletionCmd) Help() string {
	return "Install it with, for example:\n" +
		"  blackbird completion zsh > \"${fpath[1]}/_blackbird\""
}

// Boolean means "consumes no following word", which a counter does not either.
// A shell that treats -v as taking a value swallows the next word, and the word
// after -v is usually the command the user is trying to complete.
type completionFlag struct {
	Long    string   `json:"long"`
	Short   string   `json:"short,omitempty"`
	Help    string   `json:"help,omitempty"`
	Enum    []string `json:"enum,omitempty"`
	Boolean bool     `json:"boolean"`
}

type completionCommand struct {
	Path     []string            `json:"path"`
	Help     string              `json:"help,omitempty"`
	Flags    []completionFlag    `json:"flags,omitempty"`
	Commands []completionCommand `json:"commands,omitempty"`
}

type completionScript struct {
	Shell string            `json:"shell"`
	Model completionCommand `json:"model"`
	lines []string
}

func (cmd *CompletionCmd) Run(parseCtx *kong.Context, console *Console) error {
	model := completionModel(parseCtx.Model.Node, nil, nil)
	script := completionScript{Shell: cmd.Shell, Model: model}
	switch cmd.Shell {
	case "bash":
		script.lines = bashScript(model)
	case "zsh":
		script.lines = zshScript(model)
	case "fish":
		script.lines = fishScript(model)
	default:
		return usageFault("unknown shell %q", cmd.Shell)
	}
	return console.present(newView(script, drawCompletion))
}

func drawCompletion(doc *render.Document, script completionScript) {
	for _, line := range script.lines {
		doc.Raw(line)
	}
}

// completionModel flattens a Kong node into a shell-agnostic spec, omitting
// hidden commands and flags so an internal node never leaks into a shell.
//
// Two kinds of flag parse at a path without being declared on the node there.
// Kong flattens the embedded globals into the root, and they apply at every
// depth — "blackbird status --json" parses — so a node inherits its ancestors'
// flags. A node with a default subcommand accepts that subcommand's flags
// without it being named — "blackbird reservations --mode=exclusive" parses —
// so those are merged in too. Offering neither is what left whole paths
// completing nothing at all.
func completionModel(node *kong.Node, path []string, inherited []completionFlag) completionCommand {
	accepted := mergeFlags(completionFlags(node.Flags), inherited)
	command := completionCommand{Path: path, Help: node.Help, Flags: accepted}
	for _, child := range node.Children {
		if child.Hidden || child.Type == kong.ArgumentNode {
			continue
		}
		command.Commands = append(command.Commands,
			completionModel(child, append(append([]string{}, path...), child.Name), accepted))
	}
	if node.DefaultCmd != nil && !node.DefaultCmd.Hidden {
		command.Flags = mergeFlags(command.Flags, completionFlags(node.DefaultCmd.Flags))
	}
	return command
}

func completionFlags(flags []*kong.Flag) []completionFlag {
	entries := make([]completionFlag, 0, len(flags))
	for _, flag := range flags {
		if flag.Hidden {
			continue
		}
		entry := completionFlag{
			Long:    "--" + flag.Name,
			Help:    flag.Help,
			Boolean: flag.IsBool() || flag.IsCounter(),
		}
		if flag.Short != 0 {
			entry.Short = "-" + string(flag.Short)
		}
		if flag.Enum != "" {
			entry.Enum = flag.EnumSlice()
		}
		entries = append(entries, entry)
	}
	return entries
}

func mergeFlags(into, extra []completionFlag) []completionFlag {
	seen := make(map[string]bool, len(into))
	for _, flag := range into {
		seen[flag.Long] = true
	}
	for _, flag := range extra {
		if seen[flag.Long] {
			continue
		}
		seen[flag.Long] = true
		into = append(into, flag)
	}
	return into
}

// valueFlags is every spelling in the model that consumes the word after it.
// The path walk in each script skips that word: without it "inbox --limit 5"
// reads 5 as a subcommand, lands on a path no case arm matches, and completes
// nothing for the rest of the line.
func valueFlags(model completionCommand) []string {
	seen := map[string]bool{}
	for _, node := range completionNodes(model) {
		for _, flag := range node.Flags {
			if flag.Boolean {
				continue
			}
			seen[flag.Long] = true
			if flag.Short != "" {
				seen[flag.Short] = true
			}
		}
	}
	spellings := make([]string, 0, len(seen))
	for spelling := range seen {
		spellings = append(spellings, spelling)
	}
	sort.Strings(spellings)
	return spellings
}

func completionNodes(command completionCommand) []completionCommand {
	nodes := []completionCommand{command}
	for _, child := range command.Commands {
		nodes = append(nodes, completionNodes(child)...)
	}
	return nodes
}

func completionCandidates(command completionCommand) []string {
	candidates := make([]string, 0, len(command.Commands)+len(command.Flags))
	for _, child := range command.Commands {
		candidates = append(candidates, child.Path[len(child.Path)-1])
	}
	for _, flag := range command.Flags {
		candidates = append(candidates, flag.Long)
	}
	sort.Strings(candidates)
	return candidates
}

// bashScript targets bash 3.2, the /bin/bash macOS ships and the shell a
// Homebrew-first product completes under by default. Nothing here may use a
// bash 4 builtin: mapfile and readarray error out on every Tab press.
func bashScript(model completionCommand) []string {
	lines := []string{
		"_blackbird() {",
		"  local cur path index word skip candidate",
		"  COMPREPLY=()",
		`  cur="${COMP_WORDS[COMP_CWORD]}"`,
		`  local valueflags=" ` + strings.Join(valueFlags(model), " ") + ` "`,
		`  path=""`,
		"  skip=0",
		"  for (( index = 1; index < COMP_CWORD; index++ )); do",
		`    word="${COMP_WORDS[index]}"`,
		`    case "${word}" in`,
		`      "=") continue ;;`,
		"    esac",
		`    if [ "${skip}" = "1" ]; then skip=0; continue; fi`,
		`    case "${word}" in`,
		`      -*) case "${valueflags}" in *" ${word} "*) skip=1 ;; esac ;;`,
		`      *) path="${path} ${word}" ;;`,
		"    esac",
		"  done",
		`  path="${path# }"`,
		`  local candidates=""`,
		`  case "${path}" in`,
	}
	for _, node := range completionNodes(model) {
		lines = append(lines,
			`    "`+strings.Join(node.Path, " ")+`") candidates="`+strings.Join(completionCandidates(node), " ")+`" ;;`)
	}
	lines = append(lines,
		"  esac",
		`  while IFS= read -r candidate; do`,
		`    COMPREPLY[${#COMPREPLY[@]}]="${candidate}"`,
		`  done < <(compgen -W "${candidates}" -- "${cur}")`,
		"}",
		"complete -F _blackbird blackbird",
	)
	return lines
}

func zshScript(model completionCommand) []string {
	lines := []string{
		"#compdef blackbird",
		"_blackbird() {",
		"  local -a candidates",
		"  local path index word skip",
		`  local valueflags=" ` + strings.Join(valueFlags(model), " ") + ` "`,
		`  path=""`,
		"  skip=0",
		"  for (( index = 2; index < CURRENT; index++ )); do",
		`    word="${words[index]}"`,
		`    if [ "${skip}" = "1" ]; then skip=0; continue; fi`,
		`    case "${word}" in`,
		`      -*) case "${valueflags}" in *" ${word} "*) skip=1 ;; esac ;;`,
		`      *) path="${path} ${word}" ;;`,
		"    esac",
		"  done",
		`  path="${path# }"`,
		`  case "${path}" in`,
	}
	for _, node := range completionNodes(model) {
		described := make([]string, 0, len(node.Commands)+len(node.Flags))
		for _, child := range node.Commands {
			described = append(described,
				"'"+child.Path[len(child.Path)-1]+":"+describe(child.Help)+"'")
		}
		for _, flag := range node.Flags {
			described = append(described, "'"+flag.Long+":"+describe(flag.Help)+"'")
		}
		lines = append(lines,
			`    ("`+strings.Join(node.Path, " ")+`") candidates=(`+strings.Join(described, " ")+") ;;")
	}
	lines = append(lines,
		"  esac",
		"  _describe 'blackbird' candidates",
		"}",
		"compdef _blackbird blackbird",
	)
	return lines
}

func fishScript(model completionCommand) []string {
	lines := []string{"complete -c blackbird -f"}
	for _, node := range completionNodes(model) {
		condition := `-n "__fish_use_subcommand"`
		if len(node.Path) > 0 {
			condition = `-n "__fish_seen_subcommand_from ` + node.Path[len(node.Path)-1] + `"`
		}
		for _, child := range node.Commands {
			lines = append(lines, "complete -c blackbird "+condition+
				" -a "+shellQuote(child.Path[len(child.Path)-1])+" -d "+shellQuote(describe(child.Help)))
		}
		for _, flag := range node.Flags {
			line := "complete -c blackbird " + condition + " -l " + strings.TrimPrefix(flag.Long, "--")
			if flag.Short != "" {
				line += " -s " + strings.TrimPrefix(flag.Short, "-")
			}
			if !flag.Boolean {
				line += " -r"
			}
			if len(flag.Enum) > 0 {
				line += " -a " + shellQuote(strings.Join(flag.Enum, " "))
			}
			lines = append(lines, line+" -d "+shellQuote(describe(flag.Help)))
		}
	}
	return lines
}

// describe makes a help string safe to embed in a single-quoted shell literal
// and in a zsh description, where a colon separates the value from its text.
func describe(help string) string {
	replacer := strings.NewReplacer("'", "", `"`, "", ":", " -", "\n", " ")
	return strings.TrimSpace(replacer.Replace(help))
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "") + "'"
}
